// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI9emHhONkY6H4ineSBkc2WR-Whvwkb9U',
    appId: '1:469985161878:web:57ced15ae47b0fd65b48b7',
    messagingSenderId: '469985161878',
    projectId: 'homeworkauth-6ba05',
    authDomain: 'homeworkauth-6ba05.firebaseapp.com',
    storageBucket: 'homeworkauth-6ba05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsJLG4x1nIxudXmjv_a-D68hRY1oO60Oo',
    appId: '1:469985161878:android:9d78cc17c817a74e5b48b7',
    messagingSenderId: '469985161878',
    projectId: 'homeworkauth-6ba05',
    storageBucket: 'homeworkauth-6ba05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUyq-1NueYQ1sQcmpo6hD70m1j9A8T0lA',
    appId: '1:469985161878:ios:240062680a7af7285b48b7',
    messagingSenderId: '469985161878',
    projectId: 'homeworkauth-6ba05',
    storageBucket: 'homeworkauth-6ba05.appspot.com',
    iosBundleId: 'com.example.homeworkauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI9emHhONkY6H4ineSBkc2WR-Whvwkb9U',
    appId: '1:469985161878:web:6b8c48041d69c2ab5b48b7',
    messagingSenderId: '469985161878',
    projectId: 'homeworkauth-6ba05',
    authDomain: 'homeworkauth-6ba05.firebaseapp.com',
    storageBucket: 'homeworkauth-6ba05.appspot.com',
  );
}
